-- 1
SET SCHEMA FN71981@

-- 2
CREATE TABLE EMP LIKE DB2INST1.EMP@
CREATE TABLE DEPT LIKE DB2INST1.DEPT@

-- 3 
ALTER TABLE EMP ADD CONSTRAINT EMP_PK PRIMARY KEY(EMPNO)@
ALTER TABLE DEPT ADD CONSTRAINT DEPT_PK PRIMARY KEY(DEPTNO)@

ALTER TABLE EMP ADD CONSTRAINT FK_EMP_DEPT FOREIGN KEY (WORKDEPT) REFERENCES DEPT(DEPTNO)@
ALTER TABLE DEPT ADD CONSTRAINT FK_DEPT_EMP FOREIGN KEY (MGRNO) REFERENCES EMP(EMPNO)@

-- 4
INSERT INTO EMP
SELECT * FROM DB2INST1.EMP@

INSERT INTO DEPT
SELECT * FROM DB2INST1.DEPT@

-- 5

CREATE MODULE HW1@

-- 6
 
ALTER MODULE HW1
PUBLISH PROCEDURE PROC(IN in_deptno ANCHOR DEPT.DEPTNO)@

ALTER MODULE HW1 ADD PROCEDURE PROC (IN in_deptno ANCHOR DEPT.DEPTNO)
RESULT SET 1
BEGIN
DECLARE C1 CURSOR WITH RETURN FOR
SELECT D.DEPTNAME,
         M.FIRSTNME AS MGR_NAME,
         COUNT(E.EMPNO) AS CNT_EMP,
         DECIMAL(AVG(E.SALARY), 8, 2) AS AVG_SAL
          FROM EMP AS E, EMP AS M, DEPT AS D
            WHERE E.WORKDEPT = D.DEPTNO
            AND M.EMPNO = D.MGRNO
            AND E.WORKDEPT = in_deptno
       GROUP BY D.DEPTNAME, M.FIRSTNME;
     OPEN C1;
  END@
  
 

-- 7
CALL FN71981.HW1.PROC('D11')@
CALL FN71981.HW1.PROC('E21')@
