SET SCHEMA FN71981@


CREATE OR REPLACE PROCEDURE HW3(IN v_workdept ANCHOR EMP.WORKDEPT, OUT cnt INT)
BEGIN
   DECLARE table_row ANCHOR ROW EMP;
   DECLARE SQLCODE INT DEFAULT 0;
   DECLARE SQLSTATE CHAR(5) DEFAULT '00000';
   DECLARE end_table INT DEFAULT 0;
   
   DECLARE not_found CONDITION FOR SQLSTATE '02000';
   DECLARE NO_TABLE CONDITION FOR '42704';
   
   DECLARE c1 CURSOR FOR SELECT * FROM EMP
                          WHERE WORKDEPT = v_workdept;
   
   DECLARE CONTINUE HANDLER FOR not_found
     SET end_table = 1;
  
   DECLARE EXIT HANDLER FOR NO_TABLE
   INSERT INTO WARNING_MSG(MSG) VALUES ('Table does not exist');
     
     
 OPEN C1; 
  SET cnt = 0;
  FETCH c1 INTO table_row;
     
     WHILE end_table = 0 DO
      SET cnt = cnt + 1;
      FETCH c1 INTO table_row;
     END WHILE;
 CLOSE c1; 
END@  

CALL FN71981.HW3('A00', ?)@

SELECT * FROM EMP
WHERE WORKDEPT = 'A00'@

CREATE TABLE WARNING_MSG(
  MSG VARCHAR(50)
  )@
  
  DROP TABLE WARNING_MSG@
  
  SELECT * FROM WARNING_MSG@
  
 SELECT * FROM DEPT@