set schema fn71981;

CREATE VIEW INFO(DESTINATION,FROM,FLIGHTDATE)
AS
    SELECT D.CITY, F.AIRPORTNAMEDEPT, F.DEPTDATE
FROM DESTINATIONS D, FLIGHTS F
WHERE F.AIRPORTNAMEARRIVAL = D.AIRPORTNAME;


SELECT * FROM INFO;

SELECT DESTINATION AS DESTINATION, FROM AS AIRPORT, FLIGHTDATE AS DATE
FROM INFO;

CREATE VIEW INFO2(FROM,TO,DURATION, AIRLINES)
AS
    SELECT D.CITY,F.AIRPORTNAMEARRIVAL, F.DURATION, A.ANAME
    FROM DESTINATIONS D, FLIGHTS F, AIRLINES A
    WHERE F.AIRPORTNAMEDEPT = D.AIRPORTNAME
    AND F.AIRLINESNAME = A.ANAME;

SELECT  * FROM INFO2;
DROP VIEW INFO2;
