SET SCHEMA FN71981;

CREATE FUNCTION DESTINATION_NAMES(v_country varchar(50))
RETURNS  TABLE (
   CITY VARCHAR(50)
    )
RETURN
    SELECT CITY
        FROM DESTINATIONS
        WHERE COUNTRY = v_country;

SELECT *
FROM TABLE (FN71981.DESTINATION_NAMES('BULGARIA'));

SELECT * FROM FLIGHTS;

CREATE FUNCTION FLIGHT_INFO(V_FLIGHT_CODE VARCHAR(50))
RETURNS TABLE(
    DEPARTURE VARCHAR(50),
    DURATION INTEGER,
    ARRIVAL VARCHAR(50)
    )
RETURN
    SELECT AIRPORTNAMEDEPT, DURATION, AIRPORTNAMEARRIVAL
        FROM FLIGHTS
        WHERE CODE = V_FLIGHT_CODE;
SELECT *
    FROM TABLE (FN71981.FLIGHT_INFO('FB973'));
