SET SCHEMA FN71981;

CREATE TABLE AIRLINES
(
  ANAME VARCHAR(50)NOT NULL PRIMARY KEY,
  PHONE VARCHAR(10) NOT NULL,
  WEBSITE VARCHAR(20)
);
CREATE TABLE FLIGHTS(
    CODE VARCHAR(50) NOT NULL PRIMARY KEY,
    DURATION INT,
    DEPTTIME TIME NOT NULL,
    DEPTDATE DATE NOT NULL,
    ARRIVALTIME TIME NOT NULL,
    ARRIVALDATE DATE NOT NULL,
    DEPTERMINAL INT,
    ARRIVALTERMINAL INT,
    AIRLINESNAME VARCHAR(50) NOT NULL,
    AIRPORTNAMEDEPT VARCHAR(50) NOT NULL,
    AIRPORTNAMEARRIVAL VARCHAR(50) NOT NULL
);

CREATE TABLE DESTINATIONS(
  AIRPORTNAME VARCHAR(50) NOT NULL PRIMARY KEY,
  COUNTRY VARCHAR(50) NOT NULL,
  CITY VARCHAR(50) NOT NULL
);

ALTER TABLE FLIGHTS
ADD CONSTRAINT FK_FLIGHTS_AIRLINES
FOREIGN KEY (AIRLINESNAME) REFERENCES AIRLINES (ANAME);

ALTER TABLE FLIGHTS
ADD CONSTRAINT FK_FLIGHTS_DEST1
FOREIGN KEY (AIRPORTNAMEDEPT) REFERENCES DESTINATIONS(AIRPORTNAME);

ALTER TABLE FLIGHTS
ADD CONSTRAINT  FK_FLIGHTS_DEST2
FOREIGN KEY (AIRPORTNAMEARRIVAL) REFERENCES DESTINATIONS(AIRPORTNAME);

ALTER TABLE FLIGHTS
ADD CONSTRAINT CK_DATE
CHECK ( DEPTDATE < FLIGHTS.ARRIVALDATE );

ALTER TABLE FLIGHTS
ADD CONSTRAINT CK_DATE2
CHECK (DEPTDATE <= FLIGHTS.ARRIVALDATE);

ALTER TABLE FLIGHTS
DROP CHECK CK_DATE;

