SET SCHEMA DB2ADMIN@
SELECT * FROM EMPLOYEE@

CREATE PROCEDURE P71981(IN V_WORKDEPT CHAR(3), OUT V_COUNT INTEGER) 
BEGIN
     SELECT COUNT(*) INTO V_COUNT 
     FROM DB2ADMIN.EMPLOYEE
     WHERE WORKDEPT = V_WORKDEPT;
     
END @

-- CREATE PROCEDURE
CREATE PROCEDURE FN71981.DEMO1 (OUT dataIS TIMESTAMP)
LANGUAGE SQL
   SET dataIs = CURRENT_TIMESTAMP @
   
-- DELETE PROCEDURE
DROP PROCEDURE FN71981.DEMO1@


--CALL PROCEDURE
CALL FN71981.DEMO1(?) @

CREATE PROCEDURE Sample1(OUT Parm1 CHAR(10))
LANGUAGE SQL
SET Parm1 = "value1"
